import 'dart:ui';

import 'package:flame/components.dart';

import '../../snake_game.dart';

class StandartTile extends SpriteComponent with HasGameReference<SnakeGame> {
  StandartTile(Rect rect)
      : super(
    position: Vector2(rect.left, rect.top),
    size: Vector2(rect.width, rect.height),
  );

  static final List<String> spritePaths = [
    'ground/tile043.png',
    'ground/tile045.png',
    'ground/tile056.png',
    'ground/tile057.png',
    'ground/tile088.png',
    'ground/tile090.png',
    'ground/tile091.png',
    'ground/tile092.png',
    'ground/tile093.png',
    'ground/tile094.png',
    'ground/tile102.png',
    'ground/tile103.png',
    'ground/tile104.png',
    'ground/tile105.png',
    'ground/tile106.png',
    'ground/tile107.png',
    'ground/tile115.png',
    'ground/tile116.png',
    'ground/tile120.png',
    'ground/tile121.png',
    'ground/tile122.png',
    'ground/tile123.png',
    'ground/tile124.png',
    'ground/tile125.png',
    'ground/tile126.png',
    'ground/tile127.png',
    'ground/tile128.png',
    'ground/tile129.png',
    'ground/tile130.png',
    'ground/tile131.png',
    'ground/tile133.png',
    'ground/tile134.png',
    'ground/tile144.png',
    'ground/tile145.png',
    'ground/tile146.png',
    'ground/tile147.png',
    'ground/tile149.png',
    'ground/tile150.png',
    'ground/tile152.png',
    'ground/tile153.png',
    'ground/tile154.png',
    'ground/tile155.png',
    'ground/tile156.png',
    'ground/tile157.png',
    'ground/tile158.png',
    'ground/tile159.png',
    'ground/tile160.png',
    'ground/tile161.png',
    'ground/tile162.png',
    'ground/tile163.png',
    'ground/tile168.png',
    'ground/tile169.png',
    'ground/tile170.png',
    'ground/tile171.png',
    'ground/tile172.png',
    'ground/tile173.png',
    'ground/tile174.png',
    'ground/tile175.png',
    'ground/tile176.png',
    'ground/tile177.png',
    'ground/tile178.png',
    'ground/tile179.png',
    'ground/tile181.png',
    'ground/tile182.png',
    'ground/tile192.png',
    'ground/tile193.png',
    'ground/tile194.png',
    'ground/tile195.png',
    'ground/tile196.png',
    'ground/tile197.png',
    'ground/tile198.png',
    'ground/tile200.png',
    'ground/tile203.png',
    'ground/tile206.png',
    'ground/tile208.png',
    'ground/tile209.png',
    'ground/tile210.png',
    'ground/tile211.png',
    'ground/tile213.png',
    'ground/tile214.png',
    'ground/tile220.png',
    'ground/tile223.png',
    'ground/tile224.png',
    'ground/tile225.png',
    'ground/tile226.png',
    'ground/tile227.png',
    'ground/tile229.png',
    'ground/tile230.png',
    'ground/tile233.png',
    'ground/tile234.png',
    'ground/tile240.png',
    'ground/tile243.png',
    'ground/tile246.png',
    'ground/tile248.png',
    'ground/tile249.png',
    'ground/tile250.png',
    'ground/tile251.png'
  ];

  @override
  Future<void> onLoad() async {
    super.onLoad();
    sprite = game.getRandomGroundSprite();
    paint = Paint()..filterQuality = FilterQuality.none;
  }
}